### ISSUE TITLE
Add support for .Net project detection

### ISSUE THREAD

**Issue by jeffmaury** [redhat-developer/alizer#51]
The starter project (https://github.com/redhat-developer/s2i-dotnetcore-ex sub dir **app** branch **dotnet-6.0**) gives the following results:

Anayze command:
```
Language:JavaScript Frameworks: Tools: Accuracy:68.18181818181817
Language:C# Frameworks: Tools: Accuracy:13.636363636363635
Language:Smalltalk Frameworks: Tools: Accuracy:13.636363636363635
Language:GCC Machine Description Frameworks: Tools: Accuracy:4.545454545454546
```

devfile command:
`No devfile found to match`

**Comment by lstocchi** [comment]
Not sure how to handle this kind of situation. Alizer's output looks correct. If you analyze the repo, it contains 15 javascript file, 17 css, 10 html, .... , 3 c#, 3 smalltalk .... so the output is correct as it uses the percentage of files found. 
The problem is in devfile detection, it outputs a js devfile. 
The only way is to follow the same path we did in component detection... to weight languages based on configuration files, if any. In this case there is c# config file so it would appear as first in list. WDYT?

**Comment by jeffmaury** [comment]
Analyze seems to be different from what is displayed by GitHub
And yes if there is a .Net app configuration file we should consider it

**Comment by lstocchi** [comment]
Maybe they don't consider js files from lib folder (`jquery` ...) and they count .cshtml as c# file otherwise i don't have any idea about their numbers.
But .cshtml extension in language.yaml is 
```
HTML+Razor:
  type: markup
  tm_scope: text.html.cshtml
  group: HTML
  aliases:
    - razor
  extensions:
    - ".cshtml"
    - ".razor"
  ace_mode: razor
  codemirror_mode: htmlmixed
  codemirror_mime_type: text/html
  language_id: 479039817
```
and there is no relationship with c#
